# Generated by Django 5.1.5 on 2025-02-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ourvalue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstatus',
            name='title',
        ),
    ]
