# Generated by Django 5.1.5 on 2025-02-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_workstatus_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='Features2',
            new_name='Feature2',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterModelOptions(
            name='feature2',
            options={'verbose_name_plural': 'Features2'},
        ),
        migrations.AlterModelOptions(
            name='frequently',
            options={'verbose_name_plural': 'Frequentlies'},
        ),
        migrations.AlterModelOptions(
            name='workstatus',
            options={'verbose_name_plural': 'WorkStatuses'},
        ),
    ]
