# Generated by Django 5.1.5 on 2025-02-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_features_feature_rename_features2_feature2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='plan_part2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='plan_part3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='plan_part4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='plan_part5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
