# Generated by Django 5.1.5 on 2025-02-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_price_plan_part2_alter_price_plan_part3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
