# Generated by Django 5.1.5 on 2025-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='telegram',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='x',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
