# Generated by Django 5.1.5 on 2025-02-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_team_instagram_alter_team_telegram_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestClientLogo',
        ),
    ]
